### ISSUE TITLE
Initial value test with BehaviorSubject fails

### ISSUE THREAD

**Issue by soruban** [CodeSequence/jasmine-marbles#75]
Hi,

I have been trying to use jasmine-marbles in an Angular project but the following test is failing:

```
it('works', () => {
  const foo = new BehaviorSubject(1);
  const expected = cold('a', { a: 1 });
  
  expect(foo).toBeObservable(expected);
});
```

The error is as follows:

```
Error:
    Expected: a,
    Received: ?,

    Expected:
    [{"frame":0,"notification":{"kind":"N","value":1,"hasValue":true}}]

    Received:
    [{"frame":0,"notification":{"kind":"N","value":1}}],

```

The same test using TestScheduler as follows works:

```
const foo = new BehaviorSubject(1);

scheduler.run((helpers) => {
  helpers.expectObservable(foo).toBe('a', { a: 1 });
});
``` 

Any suggestions?

**Comment by marcovmun** [comment]
I think it has something todo with change: https://github.com/synapse-wireless-labs/jasmine-marbles/commit/fdbb04c8883c3704c119e4fdd8ed8db1f1c1704b#diff-9f64ee0cedd8926c3d26554ea2581eeb39327170b56700dfd63374a5c87382aaR263 (Not tested yet )

**Comment by marcovmun** [comment]
For our project it was an Angular project with rxjs version 6. So not the mandatory version 7

**Comment by soruban** [comment]
@qdelettre I was using rxjs 6.6.x & the latest version of jasmine marbles at the time so 0.9.0.

**Comment by qdelettre** [comment]
0.2.0 supports RxJS 5.x
=> 0.3.* supports RxJS 6.x
=> 0.9.0 supports RxJS 7.x

You **cannot** use 0.9.0 with rxjs < 7

**Comment by soruban** [comment]
@qdelettre My bad, I confirm this works fine when downgrading to 0.8.3.
