### ISSUE TITLE
0.8.3 instead of 0.9.0 tagged as 'latest' on npm registry.

### ISSUE THREAD

**Issue by bridzius** [CodeSequence/jasmine-marbles#83]
Hello,
Thanks for the great library!
Currently, both 0.9.0 and 0.8.3 are available on the npm registry - https://www.npmjs.com/package/jasmine-marbles - but 0.8.3 is marked as 'latest', while 0.9.0 is the 'higher' version. 0.8.3 was released more recently, but seems to lack some of the fixes available in 0.9.0.
Is this intentional?

**Comment by brandonroberts** [comment]
Yes, it's intentional. Most users (majority Angular) are still on RxJS 6.x, so we'll default to supporting that version until the shift is more towards RxJS 7.
