### ISSUE TITLE
Upgrading @latest currently stuck on 0.8.4 instead of 0.9.1

### ISSUE THREAD

**Issue by Yohandah** [CodeSequence/jasmine-marbles#92]
Using rxjs 7 and doing npm i --save-dev jasmine-marbles doesn't work because @latest is 0.8.4

![image](https://user-images.githubusercontent.com/15921402/153629290-8d23f9a5-ca0d-430e-bed2-8ebba5d9a328.png)

**Comment by martibenn** [comment]
Hi, I agree with @Yohandah remark.
Referencing this similar [issue](https://github.com/CodeSequence/jasmine-marbles/issues/83#issuecomment-886975500) => Angular supports v6 and v7 since ng v13
=> https://unpkg.com/browse/@angular/core@13.2.4/package.json

**Comment by muenchto** [comment]
Yes please fix, I was so sure that I have the latest version until  I read this issue :D

**Comment by martibenn** [comment]
Thanks !
